# Generated by Django 2.1.5 on 2019-04-28 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('claypot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='published_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('slug',)},
        ),
    ]
