# Generated by Django 2.1.5 on 2019-02-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('claypot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='images',
            field=models.ManyToManyField(to='images.Image'),
        ),
    ]
