# Generated by Django 2.1.5 on 2019-02-24 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('claypot', '0002_auto_20190224_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='published_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
