# Generated by Django 2.1.5 on 2019-04-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claypot', '0003_recipe_parent_recipe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together=set(),
        ),
    ]
