# Generated by Django 2.1.5 on 2019-04-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claypot', '0004_auto_20190428_1520'),
        ('claypot', '0003_auto_20190224_1406'),
    ]

    operations = [
    ]
