# Generated by Django 2.1.5 on 2019-05-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("claypot", "0005_auto_20190504_1424")]

    operations = [
        migrations.AlterUniqueTogether(name="recipe", unique_together={("slug",)})
    ]
