# Generated by Django 2.1.5 on 2019-05-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claypot', '0006_auto_20190504_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='estimated_waiting_duration',
            field=models.DurationField(help_text='Cooking and baking', null=True, verbose_name='Estimated waiting time'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='estimated_work_duration',
            field=models.DurationField(null=True, verbose_name='Estimated time spent working'),
        ),
    ]
