# Generated by Django 2.2.5 on 2019-10-03 13:37

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("claypot", "0011_recipe_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeDraft",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="claypot.Recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe draft",
                "verbose_name_plural": "Recipe drafts",
                "ordering": ("id",),
                "unique_together": {("author", "recipe")},
            },
        )
    ]
