# Generated by Django 2.2.2 on 2019-07-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("claypot", "0011_recipe_description")]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(null=True, verbose_name="Additional information"),
        )
    ]
