# Generated by Django 3.0 on 2019-12-25 22:41

from django.db import migrations
from django.db.models import F


def forwards(apps, schema_editor):
    if schema_editor.connection.alias != "default":
        return
    Recipe = apps.get_model("claypot", "Recipe")
    RecipeIngredient = apps.get_model("claypot", "RecipeIngredient")
    RecipeIngredientGroupIngredient = apps.get_model(
        "claypot", "RecipeIngredientGroupIngredient"
    )
    RecipeIngredientGroup = apps.get_model("claypot", "RecipeIngredientGroup")

    for recipe in Recipe.objects.all():
        # Check if the recipe has own ingredients
        if recipe.ingredients.exists():
            recipe.ingredient_groups.all().update(order=F("order") + 1)

            group = RecipeIngredientGroup.objects.create(
                recipe=recipe, title="", order=1
            )
            RecipeIngredientGroupIngredient.objects.bulk_create(
                RecipeIngredientGroupIngredient(
                    order=ingredient.order,
                    group=group,
                    ingredient=ingredient.ingredient,
                    ingredient_extra=ingredient.ingredient_extra,
                    amount_type=ingredient.amount_type,
                    amount_numeric=ingredient.amount_numeric,
                    amount_approx=ingredient.amount_approx,
                    unit=ingredient.unit,
                    optional=ingredient.optional,
                )
                for ingredient in recipe.ingredients.all()
            )


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("claypot", "0014_auto_20191225_2240"),
    ]

    operations = [migrations.RunPython(forwards), migrations.RunPython(backwards)]
