# Generated by Django 3.0 on 2019-12-28 12:32

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('claypot', '0016_auto_20191225_2343'), ('claypot', '0017_auto_20191225_2344'), ('claypot', '0018_auto_20191226_1356'), ('claypot', '0019_auto_20191226_2034')]

    dependencies = [
        ('claypot', '0015_auto_20191225_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredientgroupingredient',
            options={'verbose_name': 'Recipe ingredient', 'verbose_name_plural': 'Recipe ingredients'},
        ),
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
        migrations.RenameModel(
            old_name='RecipeIngredientGroupIngredient',
            new_name='RecipeIngredient',
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredientgroup',
            unique_together={('recipe', 'order'), ('recipe', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('group', 'ingredient')},
        ),
    ]
