# Generated by Django 3.0 on 2020-01-21 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('claypot', '0015_auto_20191225_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredientgroupingredient',
            options={'verbose_name': 'Recipe ingredient', 'verbose_name_plural': 'Recipe ingredients'},
        ),
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
        migrations.RenameModel(
            old_name='RecipeIngredientGroupIngredient',
            new_name='RecipeIngredient',
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredientgroup',
            unique_together={('recipe', 'title'), ('recipe', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('group', 'order')},
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='claypot.Ingredient', verbose_name='Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredientgroup',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='claypot.Recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredientgroup',
            unique_together={('recipe', 'order')},
        ),
    ]
