# Generated by Django 3.0 on 2019-12-29 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claypot', '0016_auto_20191225_2343_squashed_0019_auto_20191226_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientgroup',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='claypot.Recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('group', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredientgroup',
            unique_together={('recipe', 'order')},
        ),
    ]
