# Generated by Django 3.0 on 2019-12-29 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("claypot", "0016_auto_20191225_2343"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="instances",
                to="claypot.Ingredient",
                verbose_name="Ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredientgroup",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="claypot.Recipe",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recipeingredient", unique_together={("group", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="recipeingredientgroup", unique_together={("recipe", "order")},
        ),
    ]
