# Generated by Django 3.0 on 2019-12-25 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("claypot", "0016_auto_20191225_2343"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RecipeIngredientGroupIngredient", new_name="RecipeIngredient",
        ),
    ]
