# Generated by Django 3.0 on 2019-12-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("claypot", "0017_auto_20191225_2344"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="recipeingredient",
            unique_together={("group", "ingredient"), ("group", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="recipeingredientgroup",
            unique_together={("recipe", "title"), ("recipe", "order")},
        ),
    ]
