# Generated by Django 3.0 on 2019-12-26 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claypot', '0018_auto_20191226_1356'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('group', 'ingredient')},
        ),
    ]
